apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-book
  template:
    metadata:
      labels:
        app: address-book
    spec:
      containers:
        - name: address-book
          image: moyewah/address-book:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: <POSTGRES_IP>
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: addressbook
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
