name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
      - staging
      - preprod
      - prod

env:
  REGISTRY: moyewah
  IMAGE_NAME: springboot-app

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Set Environment Variables
        id: set_env_vars
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          ENV_NAME=$(echo $BRANCH_NAME | tr '-' '_' | tr '[:lower:]' '[:upper:]')

          echo "BRANCH_NAME is $BRANCH_NAME"
          echo "ENV_NAME is $ENV_NAME"

          DB_URL=''
          DB_USERNAME=''
          DB_PASSWORD=''

          if [[ "$ENV_NAME" == "MAIN" ]]; then
            DB_URL=${{ secrets.SPRING_DATASOURCE_URL }}
            DB_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
            DB_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
            echo 'main variables will be used'
          elif [[ "$ENV_NAME" == "STAGING" ]]; then
            DB_URL=${{ secrets.STAGING_SPRING_DATASOURCE_URL }}
            DB_USERNAME=${{ secrets.STAGING_SPRING_DATASOURCE_USERNAME }}
            DB_PASSWORD=${{ secrets.STAGING_SPRING_DATASOURCE_PASSWORD }}
            echo 'staging variables will be used'
          elif [[ "$ENV_NAME" == "PREPROD" ]]; then
            DB_URL=${{ secrets.PREPROD_SPRING_DATASOURCE_URL }}
            DB_USERNAME=${{ secrets.PREPROD_SPRING_DATASOURCE_USERNAME }}
            DB_PASSWORD=${{ secrets.PREPROD_SPRING_DATASOURCE_PASSWORD }}
            echo 'preprod variables will be used'
          elif [[ "$ENV_NAME" == "PROD" ]]; then
            DB_URL=${{ secrets.PROD_SPRING_DATASOURCE_URL }}
            DB_USERNAME=${{ secrets.PROD_SPRING_DATASOURCE_USERNAME }}
            DB_PASSWORD=${{ secrets.PROD_SPRING_DATASOURCE_PASSWORD }}
            echo 'prod variables will be used'
          fi
          echo "ENV_NAME is $ENV_NAME"
          echo "DB_URL is $DB_URL"
          echo "DB_USERNAME is $DB_USERNAME"
          echo "DB_PASSWORD is $DB_PASSWORD"

          echo "DB_URL=$DB_URL" >> $GITHUB_ENV
          echo "DB_USERNAME=$DB_USERNAME" >> $GITHUB_ENV
          echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV

      - name: Create namespace
        run: kubectl create namespace ${{ github.ref_name }} || true

      - name: Create Kubernetes Secrets
        run: |
          kubectl -n ${{ github.ref_name }} create secret generic db-credentials \
            --from-literal=db-url=$DB_URL \
            --from-literal=db-username=$DB_USERNAME \
            --from-literal=db-password=$DB_PASSWORD || true

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -n ${{ github.ref_name }} -f k8s/${{ github.ref_name }}/deployment.yml
          kubectl apply -n ${{ github.ref_name }} -f k8s/${{ github.ref_name }}/service.yml
